---
  - name: install epel
    yum:
      name=epel-release
      state=installed

  - name: install prereqs
    yum:
      name="{{ item }}"
      state=installed
    with_items:
      - wget
      - make
      - gcc-c++
      - autoconf
      - autoconf-archive
      - automake
      - curl-devel
      - js-devel-1.8.5
      - libicu-devel
      - libtool
      - perl-Test-Harness
      - erlang

  - name: compile and install couchdb from source
    shell: "wget http://mirrors.ibiblio.org/apache/couchdb/source/1.6.1/apache-couchdb-1.6.1.tar.gz && tar -xvf apache-couchdb-1.6.1.tar.gz && cd apache-couchdb-1.6.1 && ./configure --with-erlang=/usr/lib64/erlang/usr/include/ && make && make install"
    args:
      creates: /usr/local/var/run/couchdb

  - name: create couchdb user
    user: name=couchdb createhome=no

  - name: set ownership of couchdb directories
    file: path="{{ item }}" state=directory mode=0770 recurse=true owner=couchdb group=couchdb
    with_items:
      - /usr/local/var/lib/couchdb
      - /usr/local/var/log/couchdb
      - /usr/local/var/run/couchdb
      - /usr/local/etc/couchdb

  - name: create couchdb service
    file: path=/etc/init.d/couchdb state=link src=/usr/local/etc/rc.d/couchdb

  - name: configure couchdb to accept remote connections
    lineinfile:
          dest: "/usr/local/etc/couchdb/local.ini"
          regexp: "^#?;bind_address = 127.0.0.1"
          line: "bind_address = 0.0.0.0"

  - name: enable cors in couchdb
    blockinfile:
      dest: /usr/local/etc/couchdb/local.ini
      block: |
        [cors]
        credentials = true
        ; List of origins separated by a comma, * means accept all
        ; Origins must include the scheme: http://example.com
        ; You can’t set origins: * and credentials = true at the same time.
        origins = *
        ; List of accepted headers separated by a comma
        headers = accept, authorization, content-type, origin, referer, cache-control, x-requested-with
        ; List of accepted methods
        methods = GET, PUT, POST, HEAD, DELETE

        [httpd]
        enable_cors = true
    when: enable_cors == true

  - name: restart systemv to rescan sysv scripts
    command: systemctl daemon-reload
    ignore_errors: true

  - name: start couchdb service
    service: name=couchdb state=started enabled=yes