---
ansible:
  playbook: tests/playbook.yml
driver:
  name: docker
docker:
  containers:
    - name: groover.tomcat
      image: centos
      image_version: latest
      ansible_groups:
        - group1
verifier:
  name: testinfra
