---
# Setup handlers here:
#   Handlers may get notified at the end of the playbook ONCE
#   by tasks, e.g. restart a service on configuration change.
#   "name" attribute uses systemd syntax here as this might get
#   THE sysvinit replacement in nearly any common Linux distribution.
- name: service restart {{ tomcat_service_name }}
  become: True
  service:
    state=restarted
    name={{ tomcat_service_name }}
