# Joins the AWS Active Directory
# fixme: should it be part of AMI mostly?
- name: install AD-required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    purge: yes
    autoremove: yes
  with_items:
    - sssd
    - sssd-tools
    - libpam-winbind
    - realmd
    - libnss-sss
    - sssd-krb5
    - sssd-krb5-common
    - krb5-user
    - oddjob
    - oddjob-mkhomedir
    - adcli
    - samba-common
    - samba-common-bin
    - ntp
    - ntpdate
    - vim
    - python-pexpect

- name: Remove apt file cache
  shell: "rm -Rf /var/lib/apt/lists/*"

- name: Add server hostname to NTP service
  shell: "echo 'server $(hostname).{{ realm }}        #Default server config' >> /etc/ntp.conf"

- name: Add server hostname to Kerberos
  shell: "echo '' > /etc/krb5.conf && echo '[libdefaults]' >> /etc/krb5.conf && echo '' >> /etc/krb5.conf && echo 'default_realm = {{ realm }}' >> /etc/krb5.conf && echo 'ticket_lifetime = 24h' >> /etc/krb5.conf && echo 'renew_lifetime = 7d' >> /etc/krb5.conf"

- name: Add extra info to Samba
  shell: "echo '' > /etc/samba/smb.conf && echo '[global]' >> /etc/samba/smb.conf && echo '' >> /etc/samba/smb.conf && echo 'workgroup = {{ realm.split('.')[0] }}' >> /etc/samba/smb.conf && echo 'client signing = yes' >> /etc/samba/smb.conf && echo 'kerberos method = secrets and keytab' >> /etc/samba/smb.conf && echo 'client use spnego = yes' >> /etc/samba/smb.conf && echo 'realm = {{ realm }}' >> /etc/samba/smb.conf && echo 'security = ads' >> /etc/samba/smb.conf"

- name: Update hosts file
  shell: "echo '{{ ansible_eth0.ipv4.address }}     $(hostname)    $(hostname).{{ realm }}' >> /etc/hosts"

- name: enable services
  service: name=ntp enabled=yes state=started

- name: join ad
  shell: echo -n {{ password }} | adcli join --domain={{ domain }} --domain-realm={{ realm }} --login-user={{ ad_admin_name }}@{{ realm }} --verbose --stdin-password

- name: Set up Realmd config
  shell: "echo '[service]' > /etc/realmd.conf && echo 'automatic-install = no' >> /etc/realmd.conf"


- name: generate ticket
  shell: echo -n {{ password }} | kinit {{ ad_admin_name }}@{{ realm }}
  ignore_errors: yes

- name: Realmd domain join
  expect:
    command: "realm join -v -U {{ ad_admin_name }}@{{ realm }} {{ domain }} --install=/"
    responses:
      Password for.*: "{{ password }}"
  ignore_errors: yes

- name: change configuration of sssd
  command: sed -i 's/use_fully_qualified_names = True/use_fully_qualified_names = False/g' /etc/sssd/sssd.conf
  # todo: do we need it at all?
  ignore_errors: true

# todo: duplicates common-cloud
- name: Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: Restart sshd
