  - name: write TF
    template: src=rig_inputs.tfvars.j2 dest="{{ terraform_scripts_dir }}/rig_inputs.tfvars"

  - name: configure TF remote state
    command: terraform remote config -backend=s3 -backend-config="bucket={{bucket}}" -backend-config="key={{ module }}.tfstate" -backend-config="region={{ region }}"
    args:
      chdir: "{{ terraform_scripts_dir }}"
    tags:
    - tf

  - name: get TF modules
    command: terraform get -no-color
    args:
      chdir: "{{ terraform_scripts_dir }}"
    tags:
    - tf

  - name: run TF remote state
    command: terraform apply -no-color --var-file=rig_inputs.tfvars
    register: tf_state
    args:
      chdir: "{{ terraform_scripts_dir }}"
    tags:
    - tf

  - name: print TF output
    debug: msg={{ tf_state.stdout.split('\n') }}
    tags:
    - tf
