---

- name: config_samba | configuring samba
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 'etc/krb5.conf'
    - 'etc/resolv.conf'

- name: move original smb.conf
  shell: "mv -f /etc/samba/smb.conf /etc/samba/smb.conf.orig"

- name: config_samba | checking if domain created
  stat:
    path: "/var/log/.samba_ad_created"
  register: samba_ad_created_check

- name: nss fix (???)
  shell: "sed -i${BACKUP_SUFFIX} -e 's/passwd: .*/passwd:         files winbind/g' -e 's/group: .*/group:          files winbind/g' /etc/nsswitch.conf"

- name: config_samba | configuring Active Directory
  shell: "samba-tool domain provision --realm={{ samba_ad_info.kerberos_realm|upper }} --domain={{ samba_ad_info.netbios_domain_name }} --adminpass='{{ samba_ad_info.adminpass }}' --server-role='domain controller' --use-rfc2307 --function-level='2008_R2'"
  register: samba_ad_created
  when: >
        not samba_ad_created_check.stat.exists and
        (samba_create_domain_controller is defined and samba_create_domain_controller) and
        samba_server_role == "active directory domain controller"
  notify:
    - restart nmbd
    - restart smbd
    - restart samba-ad-dc

- name: adjust parent DNS
  lineinfile:
    dest: "/etc/samba/smb.conf"
    regexp: "dns forwarder ="
    line: "dns forwarder = {{ samba_ad_info.dns_forwarder }}"

- name: config_samba | marking domain as created
  file:
    dest: "/var/log/.samba_ad_created"
    state: touch
  when: >
        samba_ad_created.changed and
        not samba_ad_created_check.stat.exists
