- hosts: localhost
  roles:
  - { role: terraform-runner,
      module: "{{ ansible_module }}/rig",
      tags: [ tf ],
      tf_shared_vars: "{{ tf_shared }}",
      terraform_scripts_dir: "{{ tf_config_path }}"
    }
