version: "3"

services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    # environment:
    #   - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt
    #   - REGISTRY_HTTP_TLS_KEY=/certs/server.key
    ports:
      - "9000:5000"
    volumes:
      - /root/nginx/config.yml:/etc/docker/registry/config.yml:ro
      - /root/ssl:/certs:ro
  registry-web:
    image: hyper/docker-registry-web
    container_name: registry-web
    restart: unless-stopped
    links:
      - registry
    ports:
      - "8081:8080"
    volumes:
      - /root/nginx/config-web.yml:/conf/config.yml:ro
      - /root/ssl/server.key:/conf/auth.key:ro
      - /root/nginx/data:/data
  ngnix:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /root/nginx/docker-registry.conf:/etc/nginx/conf.d/default.conf:ro
      - /root/nginx/directory.html:/usr/share/nginx/html/directory.html:ro
      - /root/ssl:/usr/share/nginx/ssl:ro
      - /root/nginx/docker-registry.htpasswd:/etc/nginx/htpasswd/docker-registry.htpasswd:ro
