- name: Creating user centos with admin access
  user:
    name: "{{ ucentos }}"
    password: "{{ ucentospwd }}"
    shell: /bin/bash
    groups: root
    append: yes
    home: "{{ centos_home }}"
    createhome: yes

- name: add "{{ ucentos }}" to root group
  command: "usermod -aG root {{ ucentos }}"

- name: ensure {{ ucentos }} .ssh dir
  file: name="{{ centos_home }}/.ssh" state=directory owner={{ ucentos }} group={{ ucentos }}

- name: Add {{ ucentos }} private key
  copy: content="{{ rancher_centos_private_key }}" dest="{{ centos_home }}/.ssh/id_rsa" owner={{ ucentos }} group={{ ucentos }} mode=400

- name: Add {{ ucentos }} public key
  copy: content="{{ rancher_centos_public_key }}" dest="{{ centos_home }}/.ssh/id_rsa.pub" owner={{ ucentos }} group={{ ucentos }} mode=400
  ignore_errors: true

- name: add a {{ uusername }} public key to {{ ucentos }} authorized hosts
  authorized_key:
    user: "{{ ucentos }}"
    key: '{{ rancher_ubuntu_public_key }}'
    state: present

- name: add a rancher public key to {{ ucentos }} authorized hosts
  authorized_key:
    user: "{{ ucentos }}"
    key: '{{ rancher_public_key }}'
    state: present

- name: add a root public key to {{ ucentos }} authorized hosts
  authorized_key:
    user: "{{ ucentos }}"
    key: '{{ rancher_root_public_key }}'
    state: present

- name: add a centos public key to {{ ucentos }} authorized hosts
  authorized_key:
    user: "{{ ucentos }}"
    key: '{{ rancher_centos_public_key }}'
    state: present

- name: set ssh config for {{ ucentos }} (e.g. to disable host checking for rig domain hosts for ssh operations)
  template: src=ssh.config.j2 dest="{{ centos_home }}/.ssh/config" owner={{ ucentos }} group={{ ucentos }} mode=644
  ignore_errors: true

- name: Creating user "{{ uusername }}" with admin access
  user:
    name: "{{ uusername }}"
    password: "{{ upassword }}"
    shell: /bin/bash
    groups: root
    append: yes
    home: "{{ uhome }}"
    createhome: yes

- name: add "{{ uusername }}" to root group
  command: "usermod -aG root {{ uusername }}"

- name: ensure {{ uusername }} .ssh dir
  file: name="{{ uhome }}/.ssh" state=directory owner={{ uusername }} group={{ uusername }}

- name: Add {{ uusername }} private key
  copy: content="{{ rancher_ubuntu_private_key }}" dest="{{ uhome }}/.ssh/id_rsa" owner={{ uusername }} group={{ uusername }} mode=400

- name: Add {{ uusername }} public key
  copy: content="{{ rancher_ubuntu_public_key }}" dest="{{ uhome }}/.ssh/id_rsa.pub" owner={{ uusername }} group={{ uusername }} mode=400
  ignore_errors: true

- name: add a {{ uusername }} public key to {{ uusername }} authorized hosts
  authorized_key:
    user: "{{ uusername }}"
    key: '{{ rancher_ubuntu_public_key }}'
    state: present

- name: add a rancher public key to rancher authorized hosts
  authorized_key:
    user: "{{ uusername }}"
    key: '{{ rancher_public_key }}'
    state: present

- name: add a self root public key to rancher authorized hosts
  authorized_key:
    user: "{{ uusername }}"
    key: '{{ rancher_root_public_key }}'
    state: present

- name: add a centos public key to {{ uusername }} authorized hosts
  authorized_key:
    user: "{{ uusername }}"
    key: '{{ rancher_centos_public_key }}'
    state: present

- name: set ssh config for {{ uusername }} (e.g. to disable host checking for rig domain hosts for ssh operations)
  template: src=ssh.config.j2 dest="{{ uhome }}/.ssh/config" owner={{ uusername }} group={{ uusername }} mode=644
  ignore_errors: true

- name: add rancher to root group
  command: "usermod -aG root rancher"

- name: ensure rancher .ssh dir
  file: name="{{ rancher_home }}/.ssh" state=directory owner=rancher group=rancher

- name: Add rancher private key
  copy: content="{{ rancher_private_key }}" dest="{{ rancher_home }}/.ssh/id_rsa" owner=rancher group=rancher mode=400

- name: Add rancher public key
  copy: content="{{ rancher_public_key }}" dest="{{ rancher_home }}/.ssh/id_rsa.pub" owner=rancher group=rancher mode=400
  ignore_errors: true

- name: add a rancher public key to rancher authorized hosts
  authorized_key:
    user: rancher
    key: '{{ rancher_public_key }}'
    state: present

- name: add a self root public key to rancher authorized hosts
  authorized_key:
    user: rancher
    key: '{{ rancher_root_public_key }}'
    state: present

- name: add a centos public key to rancher authorized hosts
  authorized_key:
    user: rancher
    key: '{{ rancher_centos_public_key }}'
    state: present

- name: add a {{ uusername }} public key to rancher authorized hosts
  authorized_key:
    user: rancher
    key: '{{ rancher_ubuntu_public_key }}'
    state: present

- name: set ssh config (e.g. to disable host checking for rig domain hosts for any ssh operation)
  template: src=ssh.config.j2 dest="{{ rancher_home }}/.ssh/config" owner=rancher group=rancher mode=644
  ignore_errors: true

- name: give the rancher user a shell so it can ssh connect to the machine
  user: name=rancher shell="/bin/bash"

- name: ensure root .ssh dir
  file: name="{{ root_home }}/.ssh" state=directory owner=root group=root

- name: Add root private key
  copy: content="{{ rancher_root_private_key }}" dest="{{ rancher_home }}/.ssh/id_rsa" owner=root group=root mode=400

- name: Add root public key
  copy: content="{{ rancher_root_public_key }}" dest="{{ rancher_home }}/.ssh/id_rsa.pub" owner=root group=root mode=400
  ignore_errors: true

- name: add a rancher public key to root authorized hosts
  authorized_key:
    user: root
    key: '{{ rancher_public_key }}'
    state: present

- name: add a self root public key to root authorized hosts
  authorized_key:
    user: root
    key: '{{ rancher_root_public_key }}'
    state: present

- name: add a centos public key to root authorized hosts
  authorized_key:
    user: root
    key: '{{ rancher_centos_public_key }}'
    state: present

- name: add a {{ uusername }} public key to root authorized hosts
  authorized_key:
    user: root
    key: '{{ rancher_ubuntu_public_key }}'
    state: present

- name: insert public keys authorization in rancher cloud configuration
  become: yes
  shell: ros config set ssh_authorized_keys "['{{ rancher_ubuntu_public_key }}','{{ rancher_root_public_key }}']"
