---
- name: Install Tomcat 8 Service
  tags: tomcat
  notify: service restart {{ tomcat_service_name }}
  template:
    src=service_tomcat8_init.j2
    dest=/etc/init.d/{{ tomcat_service_name }}
    owner=0
    group=0
    mode=0755