- name: copy install_docker_extra.sh file over
  copy: src=install_docker_extra.sh dest=/tmp/install_docker_extra.sh

- name: grant permissions install_docker_extra.sh file
  shell: "chmod 777 /tmp/install_docker_extra.sh"

- name: execute install_docker_extra.sh file
  shell: "/tmp/install_docker_extra.sh"

- name: remove install_docker_extra.sh file
  file: name="/tmp/install_docker_extra.sh" state=absent owner=root group=root

- name: add "docker" group if it doesn't exist
  shell: "groupadd docker"
  ignore_errors: true

- name: add "centos" to docker group
  shell: "usermod -aG docker centos"
  ignore_errors: true

- name: ensure centos .ssh dir
  file: name="{{ centos_home }}/.ssh" state=directory owner=centos group=centos

- name: Add centos private key
  copy: content="{{ rancher_centos_private_key }}" dest="{{ centos_home }}/.ssh/id_rsa" owner=centos group=centos mode=400

- name: Add centos public key
  copy: content="{{ rancher_centos_public_key }}" dest="{{ centos_home }}/.ssh/id_rsa.pub" owner=centos group=centos mode=400
  ignore_errors: true

- name: add a rancher root public key to centos authorized hosts
  authorized_key:
    user: "centos"
    key: '{{ rancher_root_public_key }}'
    state: present

- name: add a rancher user public key to centos authorized hosts
  authorized_key:
    user: "centos"
    key: '{{ rancher_public_key }}'
    state: present

- name: add a rancher ubuntu user public key to centos authorized hosts
  authorized_key:
    user: "centos"
    key: '{{ rancher_ubuntu_public_key }}'
    state: present

- name: set ssh config for centos (e.g. to disable host checking for rig domain hosts for ssh operations)
  template: src=ssh.config.j2 dest="{{ centos_home }}/.ssh/config" owner=centos group=centos mode=644
  ignore_errors: true

- name: ensure root .ssh dir
  file: name="{{ root_home }}/.ssh" state=directory owner=root group=root

- name: Add root private key
  copy: content="{{ rancher_root_private_key }}" dest="{{ root_home }}/.ssh/id_rsa" owner=root group=root mode=400

- name: Add root public key
  copy: content="{{ rancher_root_public_key }}" dest="{{ root_home }}/.ssh/id_rsa.pub" owner=root group=root mode=400
  ignore_errors: true

- name: add a rancher public key to root authorized hosts
  authorized_key:
    user: root
    key: '{{ rancher_centos_public_key }}'
    state: present

- name: add a rancher public key to root authorized hosts
  authorized_key:
    user: root
    key: '{{ rancher_ubuntu_public_key }}'
    state: present

- name: add a rancher public key to root authorized hosts
  authorized_key:
    user: root
    key: '{{ rancher_root_public_key }}'
    state: present

- name: add a self root public key to root authorized hosts
  authorized_key:
    user: root
    key: '{{ rancher_public_key }}'
    state: present
  notify: Restart docker
