---
# defaults file for ansible-samba
pri_domain_name: 'example.org'
samba_ad_info:
  ad_dc_hostname: '{{ ansible_hostname }}'
  adminpass: '{{ adminpass }}'
  kerberos_realm: '{{ pri_domain_name }}'
  netbios_domain_name: 'EXAMPLE'
  dns_forwarder: '{{ dns_forwarder }}'
samba_allow_guests: 'yes'  #Allow users who've been granted usershare privileges to create public shares, not just authenticated ones
samba_create_domain_controller: false  #defines if you are building an Active Directory domain controller
samba_create_domain_users: false  #defines if users defined in samba_domain_users list should be created
samba_domain_users:
  - name: 'test01'
    password: 'P@55w0rd'
  - name: 'test02'
    password: 'P@55w0rd'
samba_groups:  #define samba groups to create
  - 'nogroup'
  - 'securedgroup'
  - 'testgroup'
samba_security: 'user'  #Defines samba security
samba_server_role: 'standalone server'  #defines server role...(standalone server or active directory domain controller)
samba_share_path: '/mnt/samba/shares'  #defines root folder for samba shares to be created
samba_users:  #define users to create
  - name: 'vagrant'  #define user name to create
    groups:  #define groups to add user to...ensure samba_groups names exist.
      - 'nogroup'
      - 'securedgroup'
      - 'testgroup'
    smbpasswd: 'P@55w0rd'  #define samba user password
samba_workgroup: 'EXAMPLE'
